name: first workflow

on: pull_request

jobs:
    first_job:
        name: "My workflow" 
        runs-on: ubuntu-latest

        steps:
        - name: Welcome message
          run: echo "My first github job"

        - name: list files
          run: ls -la

        - name: Read file
          run: cat Hello.txt

          

        