name: first workflow
# only deploys this workflow only on main branch 
on: 
    pull_request:
        branches: [main]

        
jobs:
    build_job:

        name: "build job" 
        runs-on: ubuntu-latest

        steps:         
        - name: Installing Cowsay
          run: sudo apt -y install cowsay

        - name: Generate ASCII Artwork
          run: cowsay -f dragon "This is a dragon" >> dragon.txt
#uploads the dragon file created for the other jobs to download it
        - name: Uploading file
          uses: action/upload-artifact@v3
          with:
            name: dragon.txt
            path: dragon.txt

    test_job:
        name: "test Job"
# the need parameter make sure this job does not run before the build-job is complete
        needs: build_job
        runs-on: ubuntu-latest

        steps:        
 # Downloads the dragon file so that dragon file exist so code does not throw an error        
        - name: Downloading file
          uses: action/download-artifact@v3
          with:
           name: dragon.txt

        - name: "Test to see file exist"
           run: grep -i "dragon" dragon.txt
 

    deploy_job:
        name: "deploy Job"
# the need parameter make sure this job does not run before the test-job is complete
        needs: test_job
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v4

 # Downloads the dragon file so that dragon file exist so code does not throw an error        
        - name: Downloading file
          uses: action/download-artifact@v3
          with:
            name: dragon.txt

        - name: list and read file
          run: | 
            echo "My first github job"
            ls -al
            cat Hello.txt 
            cat dragon.txt  
  
        - name: "Deploy"
          run: echo "deploying....."