name: first workflow

on: 
    pull_request:
        branches: [main]

        
jobs:
    first_job:

        name: "My workflow" 
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v4

          
        - name: Installing Cowsay
          run: sudo apt -y install cowsay

        - name: Generate ASCII Artwork
          run: cowsay -f dragon "This is a dragon" >> dragon.txt

        - name: list and read file
          run: | 
            echo "My first github job"
            ls -al
            cat Hello.txt 
            cat dragon.txt

        