name: Basic Workflow Dispatch Example
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to:'
        required: true
        default: 'prod'
        type: choice
        options:
          - prod
          - qa
          - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        run: echo "Deploying to ${{ github.event.inputs.environment }} environment"
